/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package minecrafteos.view.search;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class SearchJDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchJDialog.class.getName());

    /**
     * Creates new form SearchJDialog
     */
    public SearchJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSearchImage();
        setCraftingBackgroundImage();
        setFurnaceBackgroundImage();
        
        showCraftingLayeredPane(true);
        showFurnaceLayeredPane(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        furnaceLayeredPane = new javax.swing.JLayeredPane();
        craftingLayeredPane = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchButton.setBackground(new java.awt.Color(242, 242, 242));
        searchButton.setBorder(null);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout furnaceLayeredPaneLayout = new javax.swing.GroupLayout(furnaceLayeredPane);
        furnaceLayeredPane.setLayout(furnaceLayeredPaneLayout);
        furnaceLayeredPaneLayout.setHorizontalGroup(
            furnaceLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        furnaceLayeredPaneLayout.setVerticalGroup(
            furnaceLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout craftingLayeredPaneLayout = new javax.swing.GroupLayout(craftingLayeredPane);
        craftingLayeredPane.setLayout(craftingLayeredPaneLayout);
        craftingLayeredPaneLayout.setHorizontalGroup(
            craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        craftingLayeredPaneLayout.setVerticalGroup(
            craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(craftingLayeredPane)
            .addComponent(furnaceLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(craftingLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(furnaceLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setSearchImage(){
        ImageIcon imageTitle = new ImageIcon(getClass().getResource("/img/lupa.png"));
        
        Image scaled = imageTitle.getImage().getScaledInstance(
                searchButton.getWidth(), // ancho del JLabel
                searchButton.getHeight(), // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        
        this.searchButton.setIcon(new ImageIcon(scaled));
    }
    
       public void setFurnaceImageLogoPanel(Image img) {
        
        JPanel panelWithImage = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (img != null) {

                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        panelWithImage.setPreferredSize(furnaceLayeredPane.getSize());
        panelWithImage.setLayout(new BorderLayout());

        furnaceLayeredPane.setLayout(new BorderLayout());
        furnaceLayeredPane.add(panelWithImage, BorderLayout.CENTER);
        furnaceLayeredPane.revalidate();
        furnaceLayeredPane.repaint();
    }
       public void setCraftingImageLogoPanel(Image img) {
        
        JPanel panelWithImage = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (img != null) {

                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        panelWithImage.setPreferredSize(craftingLayeredPane.getSize());
        panelWithImage.setLayout(new BorderLayout());

        craftingLayeredPane.setLayout(new BorderLayout());
        craftingLayeredPane.add(panelWithImage, BorderLayout.CENTER);
        craftingLayeredPane.revalidate();
        craftingLayeredPane.repaint();
    }

    public void setCraftingBackgroundImage() {
        Image image1 = new ImageIcon(getClass().getResource("/img/crafteo.jpg")).getImage();
        setCraftingImageLogoPanel(image1);
    }
    public void setFurnaceBackgroundImage() {
        Image image1 = new ImageIcon(getClass().getResource("/img/furnace.png")).getImage();
        setFurnaceImageLogoPanel(image1);
    }
    
    public void showCraftingLayeredPane(boolean show){
        this.craftingLayeredPane.setVisible(show);
        this.pack();
    }
    public void showFurnaceLayeredPane(boolean show){
        this.furnaceLayeredPane.setVisible(show);
        this.pack();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane craftingLayeredPane;
    private javax.swing.JLayeredPane furnaceLayeredPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
