/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package minecrafteos.view.search;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import minecrafteos.model.object.ObjectM;

/**
 *
 * @author alumno
 */
public class SearchJDialog extends javax.swing.JDialog {
    private Color colorFondo = new Color(198, 198, 198);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchJDialog.class.getName());

    /**
     * Creates new form SearchJDialog
     */
    public SearchJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.getContentPane().setBackground(colorFondo);
        ((JPanel) getContentPane()).setOpaque(true);
        
        initComponents();
        setSearchImage();
        setCraftingBackgroundImage();
        setFurnaceBackgroundImage();
        
        showCraftingLayeredPane(false);
        showFurnaceLayeredPane(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        furnaceLayeredPane = new javax.swing.JLayeredPane();
        itemFurnace01Button = new javax.swing.JButton();
        itemFurnaceResultButton = new javax.swing.JButton();
        itemFurnace02Button = new javax.swing.JButton();
        craftingLayeredPane = new javax.swing.JLayeredPane();
        itemCrafting02Button = new javax.swing.JButton();
        itemCrafting01Button = new javax.swing.JButton();
        itemCrafting03Button = new javax.swing.JButton();
        itemCrafting06Button = new javax.swing.JButton();
        itemCrafting05Button = new javax.swing.JButton();
        itemCrafting08Button = new javax.swing.JButton();
        itemCrafting04Button = new javax.swing.JButton();
        itemCrafting07Button = new javax.swing.JButton();
        itemCrafting09Button = new javax.swing.JButton();
        itemCraftingResultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(198, 198, 198));

        searchPanel.setForeground(new java.awt.Color(198, 198, 198));

        searchButton.setBackground(new java.awt.Color(242, 242, 242));
        searchButton.setForeground(new java.awt.Color(198, 198, 198));
        searchButton.setBorder(null);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        furnaceLayeredPane.setForeground(new java.awt.Color(198, 198, 198));

        furnaceLayeredPane.setLayer(itemFurnace01Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        furnaceLayeredPane.setLayer(itemFurnaceResultButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        furnaceLayeredPane.setLayer(itemFurnace02Button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout furnaceLayeredPaneLayout = new javax.swing.GroupLayout(furnaceLayeredPane);
        furnaceLayeredPane.setLayout(furnaceLayeredPaneLayout);
        furnaceLayeredPaneLayout.setHorizontalGroup(
            furnaceLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(furnaceLayeredPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(furnaceLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemFurnace02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemFurnace01Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, furnaceLayeredPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemFurnaceResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        furnaceLayeredPaneLayout.setVerticalGroup(
            furnaceLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(furnaceLayeredPaneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(itemFurnace01Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(itemFurnaceResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(itemFurnace02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        craftingLayeredPane.setForeground(new java.awt.Color(198, 198, 198));

        craftingLayeredPane.setLayer(itemCrafting02Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting01Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting03Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting06Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting05Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting08Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting04Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting07Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCrafting09Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        craftingLayeredPane.setLayer(itemCraftingResultButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout craftingLayeredPaneLayout = new javax.swing.GroupLayout(craftingLayeredPane);
        craftingLayeredPane.setLayout(craftingLayeredPaneLayout);
        craftingLayeredPaneLayout.setHorizontalGroup(
            craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(craftingLayeredPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(craftingLayeredPaneLayout.createSequentialGroup()
                        .addComponent(itemCrafting07Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCrafting08Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(craftingLayeredPaneLayout.createSequentialGroup()
                        .addComponent(itemCrafting01Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCrafting02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(craftingLayeredPaneLayout.createSequentialGroup()
                        .addComponent(itemCrafting04Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemCrafting05Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemCrafting06Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCrafting03Button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCrafting09Button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemCraftingResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        craftingLayeredPaneLayout.setVerticalGroup(
            craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(craftingLayeredPaneLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCrafting03Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(itemCrafting01Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(itemCrafting02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemCrafting06Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCrafting05Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCrafting04Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemCraftingResultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(craftingLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemCrafting08Button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(itemCrafting07Button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(itemCrafting09Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(craftingLayeredPane)
            .addComponent(furnaceLayeredPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(craftingLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(furnaceLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setSearchImage(){
        ImageIcon imageTitle = new ImageIcon(getClass().getResource("/img/lupa.png"));
        
        Image scaled = imageTitle.getImage().getScaledInstance(
                searchButton.getWidth(), // ancho del JLabel
                searchButton.getHeight(), // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        searchPanel.setBackground(colorFondo);
        searchButton.setBackground(colorFondo);
        this.searchButton.setIcon(new ImageIcon(scaled));
    }
    
       public void setFurnaceImageLogoPanel(Image img) {
        
        JPanel panelWithImage = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (img != null) {
                    g.setColor(colorFondo);
                    g.fillRect(0, 0, getWidth(), getHeight());
                    
                    g.drawImage(img, 0, 0, getWidth() - 80, getHeight(), this);
                }
            }
        };

        panelWithImage.setPreferredSize(furnaceLayeredPane.getSize());
        panelWithImage.setLayout(new BorderLayout());

        furnaceLayeredPane.setLayout(new BorderLayout());
        furnaceLayeredPane.add(panelWithImage, BorderLayout.CENTER);
        furnaceLayeredPane.revalidate();
        furnaceLayeredPane.repaint();
    }
       public void setCraftingImageLogoPanel(Image img) {
        
        JPanel panelWithImage = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (img != null) {

                    g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        panelWithImage.setPreferredSize(craftingLayeredPane.getSize());
        panelWithImage.setLayout(new BorderLayout());

        craftingLayeredPane.setLayout(new BorderLayout());
        craftingLayeredPane.add(panelWithImage, BorderLayout.CENTER);
        craftingLayeredPane.revalidate();
        craftingLayeredPane.repaint();
    }
       
    public void isItemFurnace(boolean state){
        if(!state){
            showCraftingLayeredPane(true);
            showFurnaceLayeredPane(false);
        } else {
            showFurnaceLayeredPane(true);
            showCraftingLayeredPane(false);
        }
    }
    
    public void getSearchButtonActionListener(ActionListener al){
        this.searchButton.addActionListener(al);
    }
    
    public void setItemsCraftingButton(ArrayList<ObjectM> recepieCraft){
        ArrayList<String> pathsImages = new ArrayList<>();
        for(ObjectM item : recepieCraft){
            String pathImage = item.getImage();
            pathsImages.add(pathImage);
        }
        
        this.itemCrafting01Button.setIcon(new ImageIcon(this.getImageItemCraft01(pathsImages)));
        this.itemCrafting02Button.setIcon(new ImageIcon(this.getImageItemCraft02(pathsImages)));
        this.itemCrafting03Button.setIcon(new ImageIcon(this.getImageItemCraft03(pathsImages)));
        this.itemCrafting04Button.setIcon(new ImageIcon(this.getImageItemCraft04(pathsImages)));
        this.itemCrafting05Button.setIcon(new ImageIcon(this.getImageItemCraft05(pathsImages)));
        this.itemCrafting06Button.setIcon(new ImageIcon(this.getImageItemCraft06(pathsImages)));
        this.itemCrafting07Button.setIcon(new ImageIcon(this.getImageItemCraft07(pathsImages)));
        this.itemCrafting08Button.setIcon(new ImageIcon(this.getImageItemCraft08(pathsImages)));
        this.itemCrafting09Button.setIcon(new ImageIcon(this.getImageItemCraft09(pathsImages)));
        this.itemCraftingResultButton.setIcon(new ImageIcon(this.getImageItemCraftResult(pathsImages)));
    }
    
    private Image getImageItemCraft01(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(0);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft02(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(1);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft03(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(2);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft04(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(3);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft05(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(4);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft06(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(5);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft07(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(6);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft08(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(7);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraft09(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(8);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
    
    private Image getImageItemCraftResult(ArrayList<String> pathsImages){
        String pathImage = pathsImages.get(9);
        ImageIcon iconButton = new ImageIcon(getClass().getResource(pathImage));
        
        Image scaled = iconButton.getImage().getScaledInstance(
                itemCrafting01Button.getWidth() - 10, // ancho del JLabel
                itemCrafting01Button.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        return scaled;
    }
       
    private void showCraftingLayeredPane(boolean show){
        this.craftingLayeredPane.setVisible(show);
        this.pack();
    }
    private void showFurnaceLayeredPane(boolean show){
        this.furnaceLayeredPane.setVisible(show);
        this.pack();
    }

    private void setCraftingBackgroundImage() {
        Image image1 = new ImageIcon(getClass().getResource("/img/crafteo.png")).getImage();
        setCraftingImageLogoPanel(image1);
    }
    
    private void setFurnaceBackgroundImage() {
        Image image1 = new ImageIcon(getClass().getResource("/img/furnace.png")).getImage();
        setFurnaceImageLogoPanel(image1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane craftingLayeredPane;
    private javax.swing.JLayeredPane furnaceLayeredPane;
    private javax.swing.JButton itemCrafting01Button;
    private javax.swing.JButton itemCrafting02Button;
    private javax.swing.JButton itemCrafting03Button;
    private javax.swing.JButton itemCrafting04Button;
    private javax.swing.JButton itemCrafting05Button;
    private javax.swing.JButton itemCrafting06Button;
    private javax.swing.JButton itemCrafting07Button;
    private javax.swing.JButton itemCrafting08Button;
    private javax.swing.JButton itemCrafting09Button;
    private javax.swing.JButton itemCraftingResultButton;
    private javax.swing.JButton itemFurnace01Button;
    private javax.swing.JButton itemFurnace02Button;
    private javax.swing.JButton itemFurnaceResultButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the searchTextField
     */
    public javax.swing.JTextField getSearchTextField() {
        return searchTextField;
    }

    /**
     * @param searchTextField the searchTextField to set
     */
    public void setSearchTextField(javax.swing.JTextField searchTextField) {
        this.searchTextField = searchTextField;
    }
}