/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minecrafteos.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author alumno
 */
public class MainJFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setTitle("MineCrafteos");
        this.setResizable(false);
        
        setFontText();
        setBackgroundButtons();
        setBackgroundGif();
        setTitleImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initImagePanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        userButton = new javax.swing.JButton();
        createObjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setBackground(new java.awt.Color(153, 153, 153));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        userButton.setBackground(new java.awt.Color(153, 153, 153));
        userButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setText("Log Account");
        userButton.setBorder(null);

        createObjectButton.setBackground(new java.awt.Color(153, 153, 153));
        createObjectButton.setForeground(new java.awt.Color(255, 255, 255));
        createObjectButton.setText("Create object");
        createObjectButton.addActionListener(this::createObjectButtonActionPerformed);

        javax.swing.GroupLayout initImagePanelLayout = new javax.swing.GroupLayout(initImagePanel);
        initImagePanel.setLayout(initImagePanelLayout);
        initImagePanelLayout.setHorizontalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initImagePanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(initImagePanelLayout.createSequentialGroup()
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(initImagePanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(createObjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(initImagePanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(userButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        initImagePanelLayout.setVerticalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initImagePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(createObjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void createObjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createObjectButtonActionPerformed

    public JPanel getInitImagePanel() {
        return initImagePanel;
    }

    public void setInitImagePanel(JPanel initImagePanel) {
        this.initImagePanel = initImagePanel;
    }
    
    public void setBackgroundButtons(JButton button, ImageIcon icon) {
        Image scaled = icon.getImage().getScaledInstance(
                button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH
        );

        button.setIcon(new ImageIcon(scaled));
        button.setText(button.getText());

        button.setHorizontalTextPosition(SwingConstants.CENTER);
        button.setVerticalTextPosition(SwingConstants.CENTER);

        button.setBorderPainted(false);
        button.setFocusPainted(false);
        button.setContentAreaFilled(false);
    }
    
    private void setBackgroundButtons() {
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/img/buttonMC.png")
        );

        Image scaled = icon.getImage().getScaledInstance(
                searchButton.getWidth(), searchButton.getHeight(), Image.SCALE_SMOOTH
        );
        
        Image scaledUser = icon.getImage().getScaledInstance(
                userButton.getWidth(), userButton.getHeight(), Image.SCALE_SMOOTH
        );

        searchButton.setIcon(new ImageIcon(scaled));
        searchButton.setText(searchButton.getText());

        searchButton.setHorizontalTextPosition(SwingConstants.CENTER);
        searchButton.setVerticalTextPosition(SwingConstants.CENTER);

        searchButton.setBorderPainted(false);
        searchButton.setFocusPainted(false);
        searchButton.setContentAreaFilled(false);
        
        createObjectButton.setIcon(new ImageIcon(scaled));
        createObjectButton.setText(createObjectButton.getText());

        createObjectButton.setHorizontalTextPosition(SwingConstants.CENTER);
        createObjectButton.setVerticalTextPosition(SwingConstants.CENTER);

        createObjectButton.setBorderPainted(false);
        createObjectButton.setFocusPainted(false);
        createObjectButton.setContentAreaFilled(false);
        
        userButton.setIcon(new ImageIcon(scaledUser));
        userButton.setText(userButton.getText());

        userButton.setHorizontalTextPosition(SwingConstants.CENTER);
        userButton.setVerticalTextPosition(SwingConstants.CENTER);

        userButton.setBorderPainted(false);
        userButton.setFocusPainted(false);
        userButton.setContentAreaFilled(false);
    }
    
    private void setBackgroundGif() {
        ImageIcon gif = new ImageIcon(getClass().getResource("/img/background.gif"));
        JLabel backgroundLabel = new JLabel(gif);

        backgroundLabel.setLayout(new BorderLayout());
        backgroundLabel.setPreferredSize(initImagePanel.getSize());
        
        initImagePanel.setLayout(new BorderLayout());
        initImagePanel.add(backgroundLabel, BorderLayout.CENTER);
        initImagePanel.revalidate();
        initImagePanel.repaint();
    }
    
    private void setTitleImage(){
        ImageIcon imageTitle = new ImageIcon(getClass().getResource("/img/titleMainJFrame.png"));
        
        Image scaled = imageTitle.getImage().getScaledInstance(
                titleLabel.getWidth(), // ancho del JLabel
                titleLabel.getHeight(), // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        
        this.titleLabel.setIcon(new ImageIcon(scaled));
    }
    
    private void setFontText() {
        try {
            Font mcFont = Font.createFont(
                    Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/MinecraftRegular-Bmg3.otf")
            ).deriveFont(Font.PLAIN, 25f);

            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(mcFont);

            this.searchButton.setFont(mcFont);
            this.createObjectButton.setFont(mcFont);
            this.userButton.setFont(mcFont);


        } catch (FontFormatException | IOException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public void setIconUser(){
        this.userButton.setSize(65, 65);
        this.userButton.setText("");
        this.userButton.setIcon(null);
        
        ImageIcon iconUser = new ImageIcon(getClass().getResource("/img/iconUser.png"));
        
        Image scaled = iconUser.getImage().getScaledInstance(
                userButton.getWidth() - 10, // ancho del JLabel
                userButton.getHeight() - 10, // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        
        this.userButton.setIcon(new ImageIcon(scaled));
    }
    
    public void hideCreateButton(boolean show){
        this.createObjectButton.setVisible(show);
    }
    
    public void addSearchButtonActionListener(ActionListener al){
        this.getSearchButton().addActionListener(al);
    }
    
    public void addCreateObjectButtonActionListener(ActionListener al){
        this.getCreateObjectButton().addActionListener(al);
    }
    
    public void addUserButtonActionListener(ActionListener al){
        this.getUserButton().addActionListener(al);
    }
    
    public void addSearchButtonMouseListener(MouseListener ml){
        this.searchButton.addMouseListener(ml);
    }
    
    public void addCreateObjectButtonMouseListener(MouseListener ml){
        this.createObjectButton.addMouseListener(ml);
    }
    
    public void addUserButtonMouseListener(MouseListener ml){
        this.userButton.addMouseListener(ml);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createObjectButton;
    private javax.swing.JPanel initImagePanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the createObjectButton
     */
    public javax.swing.JButton getCreateObjectButton() {
        return createObjectButton;
    }

    /**
     * @return the searchButton
     */
    public javax.swing.JButton getSearchButton() {
        return searchButton;
    }

    /**
     * @return the userButton
     */
    public javax.swing.JButton getUserButton() {
        return userButton;
    }
}
