/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package minecrafteos.view.filechooser;

import java.io.File;

/**
 *
 * @author invitado
 */
public class FileChooserJDialog extends javax.swing.JDialog {

    /**
     * Creates new form FileChooserJDialog
     */
    public FileChooserJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    
    private void initListeners() {
        fileChooser.addActionListener(e -> {

             if (javax.swing.JFileChooser.APPROVE_SELECTION.equals(e.getActionCommand())) {
            dispose();
        }

        if (javax.swing.JFileChooser.CANCEL_SELECTION.equals(e.getActionCommand())) {
            fileChooser.setSelectedFile(null);
            dispose();
        }
        });
    }
    
   public File getSelectedImageFile() {
    return fileChooser.getSelectedFile();
}

    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration                   
}