/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package minecrafteos.view.create;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author dam2_alu25@inf.ald
 */
public class CreateObjectJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddJDialog
     */
    public CreateObjectJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground();
        setBackgroundButtons();
        setFontText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        initImagePanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        furnaceRadioButton = new javax.swing.JRadioButton();
        craftingTableRadioButton = new javax.swing.JRadioButton();
        typeComboBox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");

        imageLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("Imagen:");

        addButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Añadir");

        typeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Tipo:");

        buttonGroup1.add(furnaceRadioButton);
        furnaceRadioButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        furnaceRadioButton.setText("Horno");

        buttonGroup1.add(craftingTableRadioButton);
        craftingTableRadioButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        craftingTableRadioButton.setText("Mesa de Crafteo");

        typeComboBox.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Nombre:");

        nameTextField.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        fileChooserButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fileChooserButton.setForeground(new java.awt.Color(255, 255, 255));
        fileChooserButton.setText("Seleccionar...");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout initImagePanelLayout = new javax.swing.GroupLayout(initImagePanel);
        initImagePanel.setLayout(initImagePanelLayout);
        initImagePanelLayout.setHorizontalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initImagePanelLayout.createSequentialGroup()
                .addGap(0, 272, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(initImagePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(initImagePanelLayout.createSequentialGroup()
                        .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(furnaceRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(initImagePanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fileChooserButton)
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(initImagePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(craftingTableRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        initImagePanelLayout.setVerticalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(initImagePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(furnaceRadioButton)
                    .addComponent(craftingTableRadioButton))
                .addGap(61, 61, 61)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(initImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(initImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    public void setBackgroundButtons(JButton button, ImageIcon icon) {
        Image scaled = icon.getImage().getScaledInstance(
                button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH
        );

        button.setIcon(new ImageIcon(scaled));
        button.setText(button.getText());

        button.setHorizontalTextPosition(SwingConstants.CENTER);
        button.setVerticalTextPosition(SwingConstants.CENTER);

        button.setBorderPainted(false);
        button.setFocusPainted(false);
        button.setContentAreaFilled(false);
    }

    private void setFontText() {
        try {
            Font mcFont = Font.createFont(
                    Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/MinecraftRegular-Bmg3.otf")
            ).deriveFont(Font.PLAIN, 25f);

            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(mcFont);

            this.addButton.setFont(mcFont);
            this.cancelButton.setFont(mcFont);
            this.nameLabel.setFont(mcFont);
            this.imageLabel.setFont(mcFont);
            this.typeLabel.setFont(mcFont);
            this.furnaceRadioButton.setFont(mcFont);
            this.craftingTableRadioButton.setFont(mcFont);
            this.nameTextField.setFont(mcFont);
            this.fileChooserButton.setFont(mcFont);
            this.typeComboBox.setFont(mcFont);

        } catch (FontFormatException | IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void setBackground() {
        ImageIcon png = new ImageIcon(getClass().getResource("/img/Overworld_background.png"));
        JLabel backgroundLabel = new JLabel(png);

        backgroundLabel.setLayout(new BorderLayout());
        backgroundLabel.setPreferredSize(initImagePanel.getSize());

        initImagePanel.setLayout(new BorderLayout());
        initImagePanel.add(backgroundLabel, BorderLayout.CENTER);
        initImagePanel.revalidate();
        initImagePanel.repaint();
    }

    private void setBackgroundButtons() {
        ImageIcon icon = new ImageIcon(
                getClass().getResource("/img/buttonMC.png")
        );

        Image scaled = icon.getImage().getScaledInstance(
                addButton.getWidth(), addButton.getHeight(), Image.SCALE_SMOOTH
        );
        Image scaledFile = icon.getImage().getScaledInstance(
                fileChooserButton.getWidth(), fileChooserButton.getHeight(), Image.SCALE_SMOOTH
        );

        addButton.setIcon(new ImageIcon(scaled));
        addButton.setText(addButton.getText());

        addButton.setHorizontalTextPosition(SwingConstants.CENTER);
        addButton.setVerticalTextPosition(SwingConstants.CENTER);

        addButton.setBorderPainted(false);
        addButton.setFocusPainted(false);
        addButton.setContentAreaFilled(false);

        cancelButton.setIcon(new ImageIcon(scaled));
        cancelButton.setText(cancelButton.getText());

        cancelButton.setHorizontalTextPosition(SwingConstants.CENTER);
        cancelButton.setVerticalTextPosition(SwingConstants.CENTER);

        cancelButton.setBorderPainted(false);
        cancelButton.setFocusPainted(false);
        cancelButton.setContentAreaFilled(false);

        fileChooserButton.setIcon(new ImageIcon(scaledFile));
        fileChooserButton.setText(fileChooserButton.getText());

        fileChooserButton.setHorizontalTextPosition(SwingConstants.CENTER);
        fileChooserButton.setVerticalTextPosition(SwingConstants.CENTER);

        fileChooserButton.setBorderPainted(false);
        fileChooserButton.setFocusPainted(false);
        fileChooserButton.setContentAreaFilled(false);
    }

    public void addType(String item) {
        this.typeComboBox.addItem(item);
    }

    public String getTypeComboBoxItem() {
        return this.typeComboBox.getSelectedItem().toString();
    }

    public String getSelectedOption() {
        String option = null;
        if (buttonGroup1.getSelection() != null) {
            option = buttonGroup1.getSelection().getActionCommand();
        }
        return option;
    }

    public String getName() {
        return nameTextField.getText();
    }

    public void setName(String name) {
        this.nameTextField.setText(name);
    }

    public JButton getAddButton() {
        return addButton;
    }

    public void setAddButton(JButton add) {
        this.addButton = add;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public void setCancelButton(JButton cancel) {
        this.cancelButton = cancel;
    }

    public JButton getFileChooserButton() {
        return fileChooserButton;
    }

    public void setFileChooserButton(JButton fileChooser) {
        this.fileChooserButton = fileChooser;
    }

    public void addAddButtonActionListener(ActionListener al) {
        this.getAddButton().addActionListener(al);
    }

    public void addCancelButtonActionListener(ActionListener al) {
        this.getCancelButton().addActionListener(al);
    }

    public void addFileChooserActionListener(ActionListener al) {
        this.getFileChooserButton().addActionListener(al);
    }
    
    public boolean isCraftChecked() {
    return craftingTableRadioButton.isSelected();
}

public boolean isMeltChecked() {
    return furnaceRadioButton.isSelected();
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton craftingTableRadioButton;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JRadioButton furnaceRadioButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel initImagePanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    public void addCancelButtonMouseListener (MouseListener ml){
        this.cancelButton.addMouseListener(ml);
    }
    
     public void addAddButtonMouseListener (MouseListener ml){
        this.addButton.addMouseListener(ml);
    }
     
      public void addChooserButtonMouseListener (MouseListener ml){
        this.fileChooserButton.addMouseListener(ml);
    }

    
}
