/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minecrafteos.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setTitle("MineCrafteos");
        
        //setBackgroundImage();
        setBackgroundGif();
        setTitleImage();
        this.searchButton.addMouseListener(this.getPressButtonMouseListener(this.searchButton));
        this.userButton.addMouseListener(this.getPressButtonMouseListener(this.userButton));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initImagePanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        userButton = new javax.swing.JButton();
        createObjectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setBackground(new java.awt.Color(153, 153, 153));
        searchButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        userButton.setBackground(new java.awt.Color(153, 153, 153));
        userButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setText("User");

        createObjectButton.setBackground(new java.awt.Color(153, 153, 153));
        createObjectButton.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        createObjectButton.setForeground(new java.awt.Color(255, 255, 255));
        createObjectButton.setText("Create object");
        createObjectButton.addActionListener(this::createObjectButtonActionPerformed);

        javax.swing.GroupLayout initImagePanelLayout = new javax.swing.GroupLayout(initImagePanel);
        initImagePanel.setLayout(initImagePanelLayout);
        initImagePanelLayout.setHorizontalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initImagePanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(initImagePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createObjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(initImagePanelLayout.createSequentialGroup()
                        .addComponent(userButton)
                        .addGap(160, 160, 160)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        initImagePanelLayout.setVerticalGroup(
            initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initImagePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(createObjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(initImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(initImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void createObjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createObjectButtonActionPerformed

    public JPanel getInitImagePanel() {
        return initImagePanel;
    }

    public void setInitImagePanel(JPanel initImagePanel) {
        this.initImagePanel = initImagePanel;
    }
    
    public void setBackgroundGif() {
        ImageIcon gif = new ImageIcon(getClass().getResource("/img/background.gif"));
        JLabel backgroundLabel = new JLabel(gif);

        backgroundLabel.setLayout(new BorderLayout());
        backgroundLabel.setPreferredSize(initImagePanel.getSize());
        
        initImagePanel.setLayout(new BorderLayout());
        initImagePanel.add(backgroundLabel, BorderLayout.CENTER);
        initImagePanel.revalidate();
        initImagePanel.repaint();
    }
    
    public void setTitleImage(){
        ImageIcon imageTitle = new ImageIcon(getClass().getResource("/img/titleMainJFrame.png"));
        
        Image scaled = imageTitle.getImage().getScaledInstance(
                titleLabel.getWidth(), // ancho del JLabel
                titleLabel.getHeight(), // alto del JLabel
                Image.SCALE_SMOOTH // suaviza la imagen
        );
        
        this.titleLabel.setIcon(new ImageIcon(scaled));
    }
    
    private MouseListener getPressButtonMouseListener(JButton button){
        MouseListener ml = new MouseListener() {

            @Override
            public void mouseEntered(MouseEvent e) {
                System.out.println("Green");
                button.setBackground(Color.GREEN);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                System.out.println("Gray");
                button.setBackground(Color.GRAY);
            }

            @Override
            public void mouseClicked(MouseEvent e) {}

            @Override
            public void mousePressed(MouseEvent e) {}

            @Override
            public void mouseReleased(MouseEvent e) {}
        };
        return ml;
    }
    
    public void addSearchButtonActionListener(ActionListener al){
        this.searchButton.addActionListener(al);
    }
    
    public void addCreateObjectButtonActionListener(ActionListener al){
        this.createObjectButton.addActionListener(al);
    }
    
    public void addUserButtonActionListener(ActionListener al){
        this.userButton.addActionListener(al);
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createObjectButton;
    private javax.swing.JPanel initImagePanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userButton;
    // End of variables declaration//GEN-END:variables
}
